name: Cleanup GHCR
on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  delete-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'graft-hook'
          package-type: 'container'
          min-versions-to-keep: 3 # Keeps the 5 most recent builds
          delete-only-untagged-versions: true # Deletes images that no longer have a tag (like "latest")